baseURL : "https://Sameer-Jha.github.io/blogs/"
root: "posts"
languageCode : "en-us"
title : "Sam's Blog"
theme : "cupper-hugo-theme"
publishDir : "docs"

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: "Scientia potentia est"

  homeMetaContent: Experiences, Knowledge and Technology.
  footer: Made with [Love by Sam](https://sameer-jha.github.io/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true
  # A list of custom css files can be provided, which must be placed inside
  # 'static/'.
  # This is useful to override just specific css classes, instead of copying
  # the entire theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  #- css/bar.css

menu:
  nav:
    - name: Blog
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
